version: 2.1
jobs:
  build:
    docker:
      - image: krobkrong/node-yarn:0.0.2
    
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: "Prepare for testing"
          command: yarn test:prepare
      - run:
          name: "Run Jest and Collect Coverage Reports"
          command: jest --colors --coverage --collectCoverage=true

      - store_artifacts:
          path: coverage
      
      # upload report to codecov
      - run: curl https://codecov.io/bash > /bin/codecov && chmod +x /bin/codecov
      - run: codecov -f coverage/*.json -n ${CIRCLE_BUILD_NUM} -t ${CODECOV_TOKEN} -F unittests